"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Image from "next/image";

export default function Home() {
  const [inputWord, setInputWord] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const handleForge = async (e) => {
    e.preventDefault();
    if (!inputWord.trim()) return;

    setLoading(true);
    setError("");
    setResult(null);
    setCopied(false);

    try {
      const response = await fetch("/api/v1/forge", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ word: inputWord }),
      });

      if (!response.ok) {
        throw new Error("Falha ao forjar a narrativa.");
      }

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError("Ocorreu um erro ao forjar sua saga. Tente novamente.");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!result) return;
    const textToCopy = `${result.titulo}\n\n${result.historia}\n\n"${result.frase_de_ouro}"\n\nGenerated by LexiForge`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-6 md:p-24 relative overflow-hidden">
      {/* Background Ambience */}
      <div className="absolute inset-0 z-0 pointer-events-none opacity-20 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-gray-800 via-[#0B0E14] to-[#0B0E14]"></div>

      <div className="z-10 w-full max-w-3xl flex flex-col items-center gap-12 font-sans">

        {/* Header / Logo Area */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1 }}
          className="flex flex-col items-center gap-4 text-center"
        >
          <motion.div
            className="relative w-32 h-32 md:w-48 md:h-48 mb-4"
            animate={loading ? { scale: [1, 1.05, 1], opacity: [1, 0.8, 1] } : {}}
            transition={loading ? { repeat: Infinity, duration: 2, ease: "easeInOut" } : {}}
          >
            <Image
              src="/logo.png"
              alt="LexiForge Logo"
              fill
              className="object-contain drop-shadow-[0_0_15px_rgba(0,245,255,0.3)]"
              priority
            />
          </motion.div>

          {/* Logo is now the main header, but we keep the title text hidden or subtle if needed, 
                or just remove it as per "Replace text header with logo.png". 
                However, keeping the text "LEXIFORGE" below the logo is standard branding. 
                The prompt says "Substituir o cabeçalho de texto simples pela logo.png". 
                I interpret this as using the logo AS the main visual anchor, but usually the name is still present.*/}
          {/* <h1 className="text-4xl md:text-6xl font-cinzel font-bold text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-400 tracking-wider">
            LEXIFORGE
            </h1> */}
          {/* Commented out text header to strictly follow "Replace text header" instruction, 
                assuming the Logo contains the text or it's a pure visual replacement. 
                If the logo doesn't have text, I might need to keep it. 
                Let's assume standard visual: Logo image + Tagline. */}

          <p className="text-sm md:text-base text-gray-400 italic font-light tracking-widest uppercase mt-4">
            "Uma palavra entra, uma saga sai."
          </p>
        </motion.div>

        {/* Input Section */}
        <motion.form
          onSubmit={handleForge}
          className="w-full max-w-md flex flex-col items-center gap-6"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5, duration: 0.8 }}
        >
          <div className="relative w-full group">
            <div className="absolute -inset-0.5 bg-gradient-to-r from-[#00F5FF] to-purple-600 rounded-lg blur opacity-30 group-hover:opacity-75 transition duration-1000 group-hover:duration-200 animate-pulse-slow"></div>
            <input
              type="text"
              value={inputWord}
              onChange={(e) => setInputWord(e.target.value)}
              placeholder="Digite a Palavra Primordial..."
              className="relative w-full bg-[#0B0E14] text-white border border-gray-800 rounded-lg py-4 px-6 focus:outline-none focus:border-[#00F5FF] focus:shadow-[0_0_20px_rgba(0,245,255,0.2)] transition-all duration-300 text-center text-lg font-cinzel placeholder-gray-600 uppercase tracking-widest"
              maxLength={30}
              disabled={loading}
            />
          </div>

          <motion.button
            type="submit"
            disabled={loading || !inputWord.trim()}
            whileTap={{ scale: 0.95 }}
            className={`
                    px-8 py-3 rounded-full font-cinzel font-bold tracking-widest text-sm transition-all duration-300
                    ${loading || !inputWord.trim()
                ? 'opacity-50 cursor-not-allowed bg-gray-800 text-gray-500'
                : 'bg-transparent border border-[#00F5FF] text-[#00F5FF] hover:bg-[#00F5FF] hover:text-[#0B0E14] box-glow-intense'
              }
                `}
          >
            {loading ? "FORJANDO..." : "FORJAR SAGA"}
          </motion.button>
        </motion.form>

        {/* Output Section */}
        <div className="w-full min-h-[300px] flex items-center justify-center">
          <AnimatePresence mode="wait">
            {loading && (
              <motion.div
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="text-[#00F5FF] font-cinzel text-xl animate-pulse text-center"
              >
                <p>O Oráculo consulta as estrelas...</p>
                <p className="text-sm mt-2 text-gray-500 font-sans">Interpretando o significado de "{inputWord}"</p>
              </motion.div>
            )}

            {error && (
              <motion.div
                key="error"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="text-red-500 border border-red-900 bg-red-950/20 p-6 rounded-lg text-center font-cinzel"
              >
                {error}
              </motion.div>
            )}

            {result && !loading && (
              <motion.div
                key="result"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="w-full bg-[#0F1219] p-8 rounded-xl relative overflow-hidden text-center"
                style={{
                  border: '1px solid transparent',
                  borderImage: 'linear-gradient(to bottom, #374151, #00F5FF) 1'
                }}
              >
                {/* Fallback border for browsers not supporting border-image on rounded corners effectively 
                             (Note: standard border-image kills border-radius. 
                             Better approach: wrapper or pseudo element. 
                             For simplicity and reliability, using a wrapper div logic or box-shadow simulation).
                             Let's try a cleaner CSS approach with pseudo element in globals or just inline style for 'box-shadow' ring.
                             The prompt asked for "gradient border". 
                             A clean way is a background gradient buffer. 
                         */}
                <div className="absolute inset-0 rounded-xl p-[1px] bg-gradient-to-b from-gray-700 to-[#00F5FF] -z-10 pointer-events-none"></div>
                <div className="absolute inset-[1px] bg-[#0F1219] rounded-xl -z-10"></div>


                <div className="flex flex-col gap-6 relative z-10">
                  <motion.h2
                    className="text-2xl md:text-3xl font-cinzel font-bold text-[#00F5FF] mb-2 glitch-text"
                    data-text={result.titulo}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.3 }}
                  >
                    {result.titulo}
                  </motion.h2>

                  <div className="text-gray-300 font-crimson leading-relaxed text-lg text-justify md:text-center space-y-4">
                    <Typewriter text={result.historia} delay={30} />
                  </div>

                  <motion.div
                    className="mt-8 pt-6 border-t border-gray-800"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 2 }}
                  >
                    <p className="font-cinzel text-sm text-gray-500 uppercase tracking-widest mb-2">A Lenda Diz</p>
                    <p className="text-xl md:text-2xl text-white italic font-crimson">"{result.frase_de_ouro}"</p>
                  </motion.div>

                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 3 }}
                    className="mt-4 flex justify-center"
                  >
                    <button
                      onClick={handleCopy}
                      className="text-gray-500 hover:text-[#00F5FF] transition-colors text-sm font-cinzel flex items-center gap-2"
                    >
                      {copied ? (
                        <span className="text-green-400">Saga Copiada!</span>
                      ) : (
                        <>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
                          COPIAR SAGA
                        </>
                      )}
                    </button>
                  </motion.div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>
    </main>
  );
}

// Typewriter Component
const Typewriter = ({ text, delay }) => {
  const [currentText, setCurrentText] = useState("");
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    setCurrentText("");
    setCurrentIndex(0);
  }, [text, delay]);

  useEffect(() => {
    if (currentIndex < text.length) {
      const timeout = setTimeout(() => {
        setCurrentText(prevText => prevText + text[currentIndex]);
        setCurrentIndex(prevIndex => prevIndex + 1);
      }, delay);

      return () => clearTimeout(timeout);
    }
  }, [currentIndex, delay, text]);

  return <span>{currentText}</span>;
};
