"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Image from "next/image";

export default function Home() {
  const [inputWord, setInputWord] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  // Logo "Shadow Emergence"
  const logoVariants = {
    hidden: { opacity: 0, scale: 0.9, filter: "blur(8px)" },
    visible: {
      opacity: 1,
      scale: 1,
      filter: "blur(0px)",
      transition: { duration: 1.2, ease: "easeOut" }
    },
    forging: {
      scale: [1, 1.02, 1],
      filter: ["drop-shadow(0 0 0px #00F5FF)", "drop-shadow(0 0 8px #00F5FF)", "drop-shadow(0 0 0px #00F5FF)"],
      transition: { repeat: Infinity, duration: 2.5, ease: "easeInOut" }
    }
  };

  const handleForge = async (e) => {
    e.preventDefault();
    if (!inputWord.trim()) return;

    setLoading(true);
    setError("");
    setResult(null);
    setCopied(false);

    try {
      const response = await fetch("/api/v1/forge", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ word: inputWord }),
      });

      if (!response.ok) {
        throw new Error("Falha ao forjar a narrativa.");
      }

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError("Ocorreu um erro ao forjar sua saga. Tente novamente.");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!result) return;
    const textToCopy = `${result.titulo}\n\n${result.historia}\n\n"${result.frase_de_ouro}"\n\nGenerated by LexiForge`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-6 md:p-12 relative overflow-hidden bg-[#05070a]">
      {/* Zenith Noise & Ambience */}
      <div className="bg-noise"></div>
      <div className="absolute inset-0 z-0 pointer-events-none opacity-40 bg-[radial-gradient(circle_at_50%_10%,_var(--tw-gradient-stops))] from-[#0a1a2f] via-[#05070a] to-[#05070a]"></div>

      <div className="z-10 w-full max-w-3xl flex flex-col items-center gap-12 font-sans">

        {/* Header / Logo Area */}
        <motion.div
          initial="hidden"
          animate={loading ? "forging" : "visible"}
          variants={logoVariants}
          className="relative w-32 h-32 md:w-48 md:h-48 opacity-90 hover:opacity-100 transition-opacity duration-500"
        >
          <Image
            src="/logo.png"
            alt="LexiForge Logo"
            fill
            className="object-contain"
            priority
          />
        </motion.div>

        {/* Input Section - The Glass Bar */}
        <motion.form
          onSubmit={handleForge}
          className="w-full max-w-lg flex flex-col items-center gap-10"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6, duration: 1, ease: "easeOut" }}
        >
          <div className="relative w-full group flex justify-center">
            <input
              type="text"
              value={inputWord}
              onChange={(e) => setInputWord(e.target.value)}
              placeholder="DIGITE A PALAVRA..."
              className="
                        glass-bar-input
                        relative w-full 
                        text-white caret-[#00F5FF] 
                        rounded-full py-5 px-8 
                        text-center text-xl md:text-2xl font-cinzel tracking-[0.25em] uppercase
                        placeholder-gray-700 placeholder:normal-case placeholder:tracking-widest placeholder:font-light placeholder:text-sm
                        focus:outline-none focus:border-[#00F5FF]/50
                        focus:shadow-[0_10px_40px_-10px_rgba(0,245,255,0.2)]
                        transition-all duration-500 ease-out
                    "
              maxLength={30}
              disabled={loading}
            />
          </div>

          <motion.button
            type="submit"
            disabled={loading || !inputWord.trim()}
            whileTap={{ scale: 0.96 }}
            whileHover={{ scale: 1.02 }}
            className={`
                    px-10 py-3 rounded-full font-cinzel font-medium tracking-[0.3em] text-xs transition-all duration-500
                    ${loading || !inputWord.trim()
                ? 'opacity-30 cursor-not-allowed text-gray-500'
                : 'bg-transparent border border-[#00F5FF]/30 text-[#00F5FF] hover:border-[#00F5FF] hover:bg-[#00F5FF]/5 hover:shadow-[0_0_20px_rgba(0,245,255,0.15)]'
              }
                `}
          >
            {loading ? "FORJANDO..." : "FORJAR SAGA"}
          </motion.button>
        </motion.form>

        {/* Output Section */}
        <div className="w-full flex items-center justify-center min-h-[100px]">
          <AnimatePresence mode="wait">
            {loading && (
              <motion.div
                key="loading"
                initial={{ opacity: 0, filter: "blur(10px)" }}
                animate={{ opacity: 1, filter: "blur(0px)" }}
                exit={{ opacity: 0, filter: "blur(10px)" }}
                className="text-[#00F5FF]/80 font-cinzel text-sm animate-pulse text-center mt-4 space-y-3"
              >
                <p className="tracking-[0.5em] font-light">ORÁCULO DESPERTA</p>
              </motion.div>
            )}

            {error && (
              <motion.div
                key="error"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="text-red-400/80 border border-red-900/30 bg-red-950/5 p-6 rounded-2xl text-center font-cinzel text-sm mt-4 tracking-widest"
              >
                {error}
              </motion.div>
            )}

            {result && !loading && (
              <motion.div
                key="result"
                initial={{ opacity: 0, y: 40, scale: 0.98 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
                className="w-full glass-panel-zenith rounded-[2rem] p-10 md:p-14 relative overflow-hidden text-center mt-4"
              >
                <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-[#00F5FF]/20 to-transparent"></div>

                <div className="flex flex-col gap-10 relative z-10">
                  <motion.h2
                    className="text-3xl md:text-5xl font-cinzel font-normal text-white mb-2 tracking-[0.1em] drop-shadow-lg"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.3, duration: 1 }}
                  >
                    {result.titulo}
                  </motion.h2>

                  <div className="text-gray-300 font-playfair leading-[2.2] text-lg md:text-xl text-justify md:text-center space-y-6 px-2 md:px-8">
                    <Typewriter text={result.historia} delay={20} />
                  </div>

                  <motion.div
                    className="pt-10 border-t border-white/5"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: result.historia.length * 0.02 + 0.5 }}
                  >
                    <p className="font-cinzel text-[10px] text-[#00F5FF]/60 uppercase tracking-[0.4em] mb-6">A Lenda Diz</p>
                    <p className="text-xl md:text-3xl text-white/90 italic font-playfair tracking-wide leading-relaxed">"{result.frase_de_ouro}"</p>
                  </motion.div>

                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: result.historia.length * 0.02 + 1 }}
                    className=" flex justify-center pt-4"
                  >
                    <button
                      onClick={handleCopy}
                      className={`
                                        group relative overflow-hidden rounded-full px-8 py-3 transition-all duration-500
                                        ${copied ? 'bg-[#00F5FF]/10 text-[#00F5FF]' : 'bg-transparent text-gray-500 hover:text-white'}
                                    `}
                    >
                      <span className="relative z-10 flex items-center gap-3 font-cinzel text-[10px] tracking-[0.3em] font-bold">
                        {copied ? (
                          <>SAGA COPIADA</>
                        ) : (
                          <>COPIAR LENDA</>
                        )}
                      </span>
                    </button>
                  </motion.div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>

      {/* Footer / Credits */}
      <footer className="absolute bottom-6 text-center w-full z-20 opacity-40 hover:opacity-100 transition-opacity duration-500">
        <a
          href="https://github.com/ShiroiCrypto"
          target="_blank"
          rel="noopener noreferrer"
          className="text-white font-cinzel text-[10px] tracking-[0.3em]"
        >
          DESENVOLVIDO POR MATHEUS GUSTAVO
        </a>
      </footer>
    </main>
  );
}

// Typewriter Component
const Typewriter = ({ text, delay }) => {
  const [currentText, setCurrentText] = useState("");
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    setCurrentText("");
    setCurrentIndex(0);
  }, [text, delay]);

  useEffect(() => {
    if (currentIndex < text.length) {
      const timeout = setTimeout(() => {
        setCurrentText(prevText => prevText + text[currentIndex]);
        setCurrentIndex(prevIndex => prevIndex + 1);
      }, delay);

      return () => clearTimeout(timeout);
    }
  }, [currentIndex, delay, text]);

  return <span>{currentText}</span>;
};
